import img1 from "./BakeryImages/1.webp";
import img2 from './BakeryImages/2.webp';
import img3 from './BakeryImages/3.webp';
import img4 from './BakeryImages/4.webp';
import img5 from './BakeryImages/5.webp';
import img6 from './BakeryImages/6.webp';
import img7 from './BakeryImages/7.webp';
import img8 from './BakeryImages/8.webp';
import img9 from './BakeryImages/9.webp';
import img10 from './BakeryImages/10.webp';
import img12 from './BakeryImages/12.webp';
import img13 from './BakeryImages/13.webp';
import img14 from './BakeryImages/14.webp';
import img15 from './BakeryImages/15.webp';
import img16 from './BakeryImages/16.webp';
import img17 from './BakeryImages/17.webp';
import img18 from './BakeryImages/18.webp';
import img19 from './BakeryImages/19.webp';
import img20 from './BakeryImages/20.webp';
import img21 from './BakeryImages/21.webp';
import img22 from './BakeryImages/22.webp';
import img23 from './BakeryImages/23.webp';
import img24 from './BakeryImages/24.webp';
import img25 from './BakeryImages/25.webp';
import img26 from './BakeryImages/26.webp';
import img27 from './BakeryImages/27.webp';
import img28 from './BakeryImages/28.webp';
import img29 from './BakeryImages/29.webp';
import img30 from './BakeryImages/30.webp';
import img31 from './BakeryImages/31.webp';

export const Bakeryproducts = [
  {
    id: 1,
    weight: "500 ml",
    pieces: "1pc(s)",
    name: "Ritai Organic Orange Juice ",
    price: "$1.80",
    imageUrl: img1,
    category: "Juice",
    description:"Juice is a drink made from the extraction or pressing of the natural liquid contained in fruit and vegetables. It can also refer to liquids that are flavored with concentrate or other biological food sources, such as meat or seafood, such as clam juice."
  },
  {
    id: 2,
    name: "Wonderful Pomegranate Juice",
    weight: "300ml",
    pieces: "1pc(s)",
    description:"Juice is a drink made from the extraction or pressing of the natural liquid contained in fruit and vegetables. It can also refer to liquids that are flavored with concentrate or other biological food sources, such as meat or seafood, such as clam juice",
    price: "$2.40",
    imageUrl: img2,
    category: "Juice",
  },
  {
    id: 3,
    name: "Kirkland Organic Lemonade",
    weight: "150 ml",
    pieces: "1pc(s)",
    description:"Juice is a drink made from the extraction or pressing of the natural liquid contained in fruit and vegetables. It can also refer to liquids that are flavored with concentrate or other biological food sources, such as meat or seafood, such as clam juice",
    price: "$1.50",
    imageUrl: img3,
    category: "Juice",
  },
  {
    id: 4,
    name: "Sun Tropics Organic Mango,",
    weight: "250 ml",
    pieces: "1pc(s)",
    description:"Juice is a drink made from the extraction or pressing of the natural liquid contained in fruit and vegetables. It can also refer to liquids that are flavored with concentrate or other biological food sources, such as meat or seafood, such as clam juice",
    price: "$2.25",
    imageUrl: img4,
    category: "Juice",
  },
  {
    id: 5,
    name: "Pressed Juicery Super Citrus Plus",
    weight: "200ml",
    pieces: "1pc(s)",
    description:"Juice is a drink made from the extraction or pressing of the natural liquid contained in fruit and vegetables. It can also refer to liquids that are flavored with concentrate or other biological food sources, such as meat or seafood, such as clam juice",
    price: "$1.25",
    imageUrl: img5,
    category: "Juice",
  },
  {
    id: 6 ,
    name: "Kirkland Cranberry Juice Cocktail",
    weight: "200ml",
    pieces: "1pc(s)",
    description:"Juice is a drink made from the extraction or pressing of the natural liquid contained in fruit and vegetables. It can also refer to liquids that are flavored with concentrate or other biological food sources, such as meat or seafood, such as clam juice",
    price: "$2.00",
    imageUrl: img6,
    category: "Juice",
  },
  {
    id:7 ,
    name: "Freshly Brewed Organic Green Tea",
    weight: "",
    pieces: "1pc(s)",
    description:"Juice is a drink made from the extraction or pressing of the natural liquid contained in fruit and vegetables. It can also refer to liquids that are flavored with concentrate or other biological food sources, such as meat or seafood, such as clam juice",
    price: "$0.50",
    imageUrl: img7,
    category: "Juice",
  },
  {
    id: 8,
    name: "Fresh Grinded Frappé coffee,",
    weight: "50ml",
    pieces: "1pc(s)",
    description:"Coffee tea refers to herbal tea made from non-bean parts of the coffea (coffee plant), and may refer to: Coffee-leaf tea · Coffee cherry tea. Ground coffee, brewed",
    price: "$1.25",
    imageUrl: img8,
    category: "Coffee & Tea",
  },
  {
    id: 9,
    name: "Caffee Nero Mocha Late ",
    weight: "50ml",
    pieces: "1pc(s)",
    description:"Coffee tea refers to herbal tea made from non-bean parts of the coffea (coffee plant), and may refer to: Coffee-leaf tea · Coffee cherry tea. Ground coffee, brewed",
    price: "$1.50",
    imageUrl: img9,
    category: "Coffee & Tea",
  },
  {
    id: 10,
    name: "Fresh Traditional English Tea",
    weight: "",
    pieces: "1pc(s)",
    description: "Coffee tea refers to herbal tea made from non-bean parts of the coffea (coffee plant), and may refer to: Coffee-leaf tea · Coffee cherry tea. Ground coffee, brewed",
    price: "$0.50",
    imageUrl: img10,
    category: "Coffee & Tea",
  },
  {
    id: 11,
    name: "Freshly Brewed Black Coffee",
    weight: "",
    pieces: "1pc(s)",
    description: "Coffee tea refers to herbal tea made from non-bean parts of the coffea (coffee plant), and may refer to: Coffee-leaf tea · Coffee cherry tea. Ground coffee, brewed",
    price: "$0.50",
    imageUrl: img12,
    category: "Coffee & Tea",
  },
  {
    id: 12,
    name: "Freshly Brewed Black Coffee",
    weight: "",
    pieces: "1pc(s)",
    description: "Coffee tea refers to herbal tea made from non-bean parts of the coffea (coffee plant), and may refer to: Coffee-leaf tea · Coffee cherry tea. Ground coffee, brewed",
    price: "$0.50",
    imageUrl: img13,
    category: "Coffee & Tea",
  }, 
  {
    id: 13,
    name: "Peet Coffee Decaf Major Dickason,",
    weight: "2 lb",
    pieces: "1pc(s)",
    description: "Coffee tea refers to herbal tea made from non-bean parts of the coffea (coffee plant), and may refer to: Coffee-leaf tea · Coffee cherry tea. Ground coffee, brewed",
    price: "$2.50",
    imageUrl: img14,
    category: "Coffee & Tea",
  },
  {
    id: 14,
    name: "Raspberry Crumble Cookies ",
    weight: "300g",
    pieces: "1pc(s)",
    description: "Coffee tea refers to herbal tea made from non-bean parts of the coffea (coffee plant), and may refer to: Coffee-leaf tea · Coffee cherry tea. Ground coffee, brewed",
    price: "$3.50",
    imageUrl: img15,
    category: "Cookies",
  },
  {
    id: 15,
    name: "Chocolate Chip Cookie",
    weight: "250g",
    pieces: "1pc(s)",
    description:"A cookie is a baked or cooked food that is typically small, flat and sweet. It usually contains flour, sugar and some type of oil or fat. It may include other ingredients such as raisins, oats, chocolate chips, nuts. ",
    price: "$2.50",
    imageUrl: img16,
    category: "Cookies",
  },
  {
    id: 16,
    name: "Freshly Baked Chocolate Chip Cookie",
    weight: "250g",
    pieces: "1pc(s)",
    description:"A cookie is a baked or cooked food that is typically small, flat and sweet. It usually contains flour, sugar and some type of oil or fat. It may include other ingredients such as raisins, oats, chocolate chips, nuts. ",
    price: "$4.50",
    imageUrl: img17,
    category: "Cookies",
  },
  {
    id: 17,
    name: "Freshly Baked Mixed Cookies",
    weight: "490g",
    pieces: "1pc(s)",
    description:"A cookie is a baked or cooked food that is typically small, flat and sweet. It usually contains flour, sugar and some type of oil or fat. It may include other ingredients such as raisins, oats, chocolate chips, nuts. ",
    price: "$4.50",
    imageUrl: img18,
    category: "Cookies",
  },
  {
    id: 18,
    name: "Freshly Baked Mixed Cookies, ",
    weight: "890g",
    pieces: "1pc(s)",
    description:"A cookie is a baked or cooked food that is typically small, flat and sweet. It usually contains flour, sugar and some type of oil or fat. It may include other ingredients such as raisins, oats, chocolate chips, nuts. ",
    price: "$7.00",
    imageUrl: img19,
    category: "Cookies",
  },
  {
    id: 19,
    name: "Freshly Baked Raspberry Cookies",
    weight: "250g",
    pieces: "1pc(s)",
    description:"A cookie is a baked or cooked food that is typically small, flat and sweet. It usually contains flour, sugar and some type of oil or fat. It may include other ingredients such as raisins, oats, chocolate chips, nuts. ",
    price: "$3.50",
    imageUrl: img20,
    category: "Cookies",
  },
  {
    id: 20,
    name: "Signature Chocolate Cake Iced Fudge",
    weight: "7 oz",
    pieces: "1pc(s)",
    description:"Cake is a form of sweet food made from flour, sugar, and other ingredients, that is usually baked. In their oldest forms, cakes were modifications of bread, but cakes now cover a wide range of preparations",
    price: "$11.75",
    imageUrl: img21,
    category: "Cakes",
  },
  {
    id: 21,
    name: "Desserts Cake, Raspberry Dark Chocolate ",
    weight: "2 lb",
    pieces: "1pc(s)",
    description:"Cake is a form of sweet food made from flour, sugar, and other ingredients, that is usually baked. In their oldest forms, cakes were modifications of bread, but cakes now cover a wide range of preparations",
    price: "$12.00",
    imageUrl: img22,
    category: "Cakes",
  },
  {
    id: 22,
    name: "Cafe Valley Triple Chocolate Cake",
    weight: " 4 lb",
    pieces: "1pc(s)",
    description:"Cake is a form of sweet food made from flour, sugar, and other ingredients, that is usually baked. In their oldest forms, cakes were modifications of bread, but cakes now cover a wide range of preparations",
    price: "$12.00",
    imageUrl: img23,
    category: "Cakes",
  },
  {
    id: 23,
    name: "Signature German Chocolate Cake ",
    weight: "4 lb",
    pieces: "1pc(s)",
    description:"Cake is a form of sweet food made from flour, sugar, and other ingredients, that is usually baked. In their oldest forms, cakes were modifications of bread, but cakes now cover a wide range of preparations",
    price: "$10.00",
    imageUrl: img24,
    category: "Cakes",
  },
  {
    id: 24,
    name: "Rubics Bakery Strawberry 3 Layer Cake",
    weight: " 21 oz",
    pieces: "1pc(s)",
    description:"Cake is a form of sweet food made from flour, sugar, and other ingredients, that is usually baked. In their oldest forms, cakes were modifications of bread, but cakes now cover a wide range of preparations",
    price: "$7.20",
    imageUrl: img25,
    category: "Cakes",
  },
  {
    id: 25,
    name: "One Layer Decorated Chocolate Cake ",
    weight: "1.3 lb",
    pieces: "1pc(s)",
    description:"Cake is a form of sweet food made from flour, sugar, and other ingredients, that is usually baked. In their oldest forms, cakes were modifications of bread, but cakes now cover a wide range of preparations",
    price: "$7.00",
    imageUrl: img26,
    category: "Cakes",
  },
  {
    id: 26,
    name: "Al Shams Pita Bread, 10 pcs",
    weight: "",
    pieces: "10pc(s)",
    description:"JPita or pitta, is a family of yeast-leavened round flatbreads baked from wheat flour, common in the Mediterranean, Middle East, and neighboring areas",
    price: "$2.00",
    imageUrl: img27,
    category: "Pita Bread",
  },
  {
    id: 27,
    name: "Garlic Filled Pita Bread",
    weight: "",
    pieces: "10pc(s)",
    description:"JPita or pitta, is a family of yeast-leavened round flatbreads baked from wheat flour, common in the Mediterranean, Middle East, and neighboring areas",
    price: "$1.80",
    imageUrl: img28,
    category: "Pita Bread",
  },
  {
    id: 28,
    name: "Giannis Big Pita Bread",
    weight: "",
    pieces: "5pc(s)",
    description:"JPita or pitta, is a family of yeast-leavened round flatbreads baked from wheat flour, common in the Mediterranean, Middle East, and neighboring areas",
    price: "$2.00",
    imageUrl: img29,
    category: "Pita Bread",
  },
  {
    id: 29,
    name: "Alamir Bakery Pita Bread",
    weight: "",
    pieces: "10pc(s)",
    description:"JPita or pitta, is a family of yeast-leavened round flatbreads baked from wheat flour, common in the Mediterranean, Middle East, and neighboring areas",
    price: "$2.50",
    imageUrl: img30,
    category: "Pita Bread",
  },
  {
    id: 30,
    name: "Joseph's Flax Whole Wheat Pita Bread",
    weight: "",
    pieces: "5pc(s)",
    description:"JPita or pitta, is a family of yeast-leavened round flatbreads baked from wheat flour, common in the Mediterranean, Middle East, and neighboring areas",
    price: "$2.25",
    imageUrl: img31,
    category: "Pita Bread",
  },
]